baseurl = "https://andersschmidt.netlify.com/"
title = "ANDERS S. SCHMIDT"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Anders Sjørslev Schmidt's personal website"
  copyright = "&copy;2018 Anders Sjørslev Schmidt"
  sidebarAbout = [ "M.D./PhD-candidate at Aarhus University",
  "Follow ongoing research projects and recent activities. Blog about Medicine, Data science with passion for R and personal views on fun stuff and life in general - opinions are my own!"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About me"
  url = "about/"

  [[params.navlinks]]
  name = "Atrial Fibrillation Research Team"
  url = "af-research/"

   [[params.navlinks]]
  name = "Curriculum Vitae"
  url = "docs/CV Anders Schmidt.pdf"

  #  [[params.navlinks]]
  #name = "Get in touch"
  #url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
